#!/usr/bin/env bash
set -e # halt script on error

cd docs
make clean html
bundle exec htmlproofer --check-html ./.build/html/ --allow-hash-href --file-ignore ./.build/html/search.html --url-ignore /localhost/,/0.0.0.0/,/horizon.example/

