#!/usr/bin/env bash
set -e # halt script on error

mkdocs build
bundle exec htmlproofer  --check-html ./site/ --file-ignore ./site/base.html,./site/breadcrumbs.html,./site/footer.html,./site/toc.html,./site/versions.html
