# -*- coding: utf-8 -*-
#
# Quattor documentation build configuration file

# General information about the project.
# (Most of it is required but rendering on the website is disabled later on.)
project = u'Quattor'
copyright = u'2017, Quattor Community'
author = u'Quattor Community'
version = u'0.0.1'
release = u'0.0.1'

# Set build options
master_doc = 'index'
show_authors = False
language = None
# Required as we overwrite localtoc and globaltoc
templates_path = ['_templates']
exclude_patterns = ['.build', 'Thumbs.db', '.DS_Store']
pygments_style = 'sphinx'
todo_include_todos = False

# html build options. Use the color scheme and font of quattor.org.
html_theme = 'classic'
html_title = project
html_theme_options = {
    "relbarbgcolor": "#333",
    "sidebarbgcolor": "#333",
    "footerbgcolor": "#333",
    "headtextcolor": "#333",
    "bodyfont": "'Lato', 'Helvetica', sans-serif",
    "headfont": "'Lato', 'Helvetica', sans-serif",
    "body_max_width": None,
}

# Include the logo.
html_logo='quattor_logo_navbar.png'
# for good measure but readthedocs overwrites it.
html_favico='favicon.ico'
html_show_sphinx=False
html_show_copyright=False
htmlhelp_basename = 'Quattordocs'

# Overwrite sidebars to a more sane setup.
html_sidebars = {
   # Keep the landing page clean.
   'index': ['globaltoc.html', 'searchbox.html'],
   # Show page toctree and add links for 'next' and 'previous'.
   '*/*': ['localtoc.html', 'globaltoc.html', 'relations.html', 'searchbox.html'],
   # No relations in the section pages
   'toc_*': ['localtoc.html', 'globaltoc.html', 'searchbox.html'],
   # Make sure a link back exists on the search page.
   'search': ['globaltoc.html'],
}

# Disable autogenerated indexes as we do it ourselves.
html_use_modindex = False
html_use_index = False

# Latex options.
latex_documents = [
    (master_doc, 'Quattor.tex', u'Quattor Documentation',
     u'Quattor Community', 'manual'),
]
texinfo_documents = [
    (master_doc, 'Quattor', u'Quattor Documentation',
     author, 'Quattor', 'Deployment made easy.',
     'Miscellaneous'),
]
